### PR TITLE
Create BMS GUI

### PR DESCRIPTION
**Pull request by hansenkw**

### CODE REVIEW

**Comment by a2k-hanlon** [comment]
Hi Hansen, could you please add the following lines to the .gitignore file in the tools/gui folder and make sure all the .pyc and .csv files are removed from the PR?


*.pyc
*.csv

**Comment by hansenkw** [comment]
Hi Andrew, 
Yeah, I'll add those lines. By the way, what is PR?
Regards, Christophorus Hansen
    On Sunday, October 3, 2021, 10:42:29 PM PDT, Andrew Hanlon ***@***.***> wrote:  
 
 


Hi Hansen, could you please add the following lines to the .gitignore file in the tools/gui folder and make sure all the .pyc and .csv files are removed from the PR?

*.pyc
*.csv

**Comment by a2k-hanlon** [comment]
Okay, thank you. PR is short for pull request.

**Review by a2k-hanlon — APPROVED** [review]
Okay Hansen, thanks for going over this with me. I just tweaked a bit of whitespace and README content but otherwise this PR is ready to go. I will merge this branch now.

@abooodeee Thank you once again for all of your work on this awesome tool!

**Pull request merged**
